# Generated by Django 4.1.2 on 2022-11-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='сlient',
            options={'ordering': ['name_client', 'citi']},
        ),
    ]
